import EditableGridLayout from './EditableGridLayout';

export const dashboardLayout = [
  {
    title: 'Actuator',
    link: '/',
    description: '온실내 장치의 작동상태를 확인할 수 있습니다.',
    chart: 'ActuatorStat',
    i: '22',
    x: 0,
    y: 0,
    w: 2,
    h: 6,
    static: false,
    moved: false,
  },
  {
    title: 'EC',
    link: '/dashboard/temperature_detail',
    description: 'EC. ',
    chart: 'WaterEcNow',
    i: '23',
    x: 10,
    y: 5,
    w: 2,
    h: 1,
    static: false,
    moved: false,
  },
  {
    title: 'VPD',
    link: '/dashboard/vpd_detail',
    description: '현 시잠의 VPD를 scatter 챠트로  표시합니다. ',
    chart: 'VPDNow',
    i: '24',
    x: 8,
    y: 3,
    w: 2,
    h: 3,
    static: false,
    moved: false,
  },
  {
    title: 'Temperature',
    link: '/dashboard/temperature_detail',
    description: '현재 온실온도를 게이지로 표시한다.',
    chart: 'TemperatureNowGauge',
    i: '25',
    x: 2,
    y: 0,
    w: 2,
    h: 3,
    static: false,
    moved: false,
  },
  {
    title: 'pH',
    link: '/dashboard/temperature_detail',
    description: '온실평균 온도를 표시한다. ',
    chart: 'WaterPHNow',
    i: '27',
    x: 10,
    y: 3,
    w: 2,
    h: 2,
    static: false,
    moved: false,
  },
  {
    title: 'RTR',
    link: '/dashboard/rtr_detail',
    description: 'RTR 을 표시합니다. RTR 은 DLI 와 온도에 따라 달라집니다.  ',
    chart: 'RTR',
    i: '28',
    x: 6,
    y: 3,
    w: 2,
    h: 3,
    static: false,
    moved: false,
  },
  {
    title: 'Light',
    link: '/dashboard/light_detail',
    description: '현 시잠의 광량을  게이지  챠트로  표시합니다. ',
    chart: 'LightNowGauge',
    i: '30',
    x: 6,
    y: 0,
    w: 2,
    h: 3,
    static: false,
    moved: false,
  },
  {
    title: 'DLI',
    link: '/dashboard/light_detail',
    description: '일단위 외부누적광량과 DLI 추정치를 라인챠트로  표시합니다. ',
    chart: 'DLI',
    i: '31',
    x: 2,
    y: 3,
    w: 2,
    h: 3,
    static: false,
    moved: false,
  },
  {
    title: 'RH',
    link: '/dashboard/humidity_detail',
    description: '현 시잠의 상대습도를 게이지  챠트로  표시합니다. ',
    chart: 'HumidityNowGauge',
    i: '32',
    x: 4,
    y: 0,
    w: 2,
    h: 3,
    static: false,
    moved: false,
  },
  {
    title: 'CO2',
    link: '/dashboard/co2_detail',
    description: '이산화탄소 농도를 게이지로 표시합니다.',
    chart: 'Co2NowGauge',
    i: '33',
    x: 8,
    y: 0,
    w: 2,
    h: 3,
    static: false,
    moved: false,
  },
  {
    title: 'Irrigation amount',
    link: '/dashboard/temperature_detail',
    description: '일단위 누적 관수량 및 관수횟수를 표시한다.',
    chart: 'Watering',
    i: '34',
    x: 10,
    y: 0,
    w: 2,
    h: 3,
    static: false,
    moved: false,
  },
  {
    title: 'PhotoPeriod',
    link: '/',
    description: 'No Description',
    chart: 'PhotoPeriod',
    i: '35',
    x: 4,
    y: 3,
    w: 2,
    h: 3,
    static: false,
    moved: false,
  },
];

export default function GridLayoutTest() {
  const layoutId = 'first_page';
  return (
    <div className={'w-full h-full flex flex-col box-border'}>
      <EditableGridLayout
        key={Math.random()}
        id={layoutId}
        defaultLayout={dashboardLayout}
      />
    </div>
  );
}
